name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Lint the code
      - name: Lint
        run: npm run lint

      # Run tests with coverage
      - name: Run tests with coverage
        run: npm test -- --coverage
        env:
          CI: true

  check-coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Check out the code
      - uses: actions/checkout@v3

      # Check test coverage
      - name: Check test coverage
        run: |
          if [ ! -f ./coverage/coverage-summary.json ]; then
            echo "Coverage report not found!"
            exit 1
          fi
          echo "Coverage report found"
          COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
          echo "Test coverage is ${COVERAGE}%"
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
            echo "Test coverage is below 90%, cannot deploy."
            exit 1
          fi

  build-and-deploy:
    needs: check-coverage
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build dist
        run: npm run build

      # Setup GitHub Pages configuration
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Upload build artifacts to GitHub Pages
      - name: Upload dist folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
